name: Call a reusable workflow and use its outputs

on:
  # Merges to main
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    uses: Ssases/example-voting-app/.github/workflows/RW.yml@master

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }
