on:
  workflow_dispatch:

jobs:
  job1:
    name: "Call other workflow"
    uses: Ssases/example-voting-app/.github/workflows/RW.yml@master
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Print my_var"
        run: echo my_var [${{needs.job1.outputs.my_var}}]
