on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request: 

jobs:
  job1:
    name: "Tag-Manage"
    uses: Ssases/example-voting-app/.github/workflows/RW.yml@master
  
  job2:
    name: "Helm-Lint"
    needs: job1
    uses: Ssases/reusable-workflows/.github/workflows/helm_lint.yml@main
        
  job3:
    name: "Helm Push"
    needs: [job1, job2]
    uses: Ssases/reusable-workflows/.github/workflows/helm-process.yml@main
    with:
      helm_package: helm/example-voting-app
      version: ${{needs.job1.outputs.computedTag_prod}}
    
 
