on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    name: "Call other workflow"
    uses: Ssases/example-voting-app/.github/workflows/RW.yml@master
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Print tag"
        run: echo ${{needs.job1.outputs.tag}}
        
  job3:
      uses: Ssases/reusable-workflows/.github/workflows/helm-process.yml@main
      with:
        helm_package: helm/example-voting-app
        version: ${{needs.job1.outputs.tag}}

