name: Output

on:
  # Merges to main
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
jobs:  
  job1: 
    name: "Call other workflow"
    uses: Ssases/example-voting-app/.github/workflows/output.yml@main
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Print my_var"
      - run: echo my_var [${{needs.my_job.outputs.my_var}}]
