name: Output

on:
  # Merges to main
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
jobs:  
  my_job:
    runs-on: ubuntu-latest
    outputs:
      # Map the step outputs to job outputs
      my_var: ${{steps.my_step.outputs.my_var}}
    steps:
      - name: "Example output creation"
        id: "my_step"
        run: |
          my_var="Hello World"
          echo "Output [$my_var]"
          echo "my_var=$my_var" >> $SIVA
  my_second_job:
    runs-on: ubuntu-latest
    needs: my_job
    steps:
      - run: echo my_var [${{needs.my_job.outputs.my_var}}]
