name: Tag manage

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      computedTag:
        description: "The computed tag output string"
        value: ${{ jobs.tag-manage.outputs.output1 }}
     
jobs:
  tag-manage:
    name: Generate Tag output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      tagversiondev: ${{ steps.step1.outputs.TAG }}
    steps:
      - id: step1
        run: |
          echo $(( $RANDOM % 500000 + 600000 ))
          TAG=$( echo $(( $RANDOM % 500000 + 600000 )))
          echo "TAG=${TAG}" >> GIT_OUTPUT
      
