name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      computedTag:
        description: "The first output string"
        value: ${{ jobs.tag_manage.outputs.tag_version }}
        
jobs:
  tag_manage:
      name: Generate output
      runs-on: ubuntu-latest
      # Map the job outputs to step outputs
      outputs:
        tag_version: ${{ steps.prod.outputs.GIT_TAG }}
      steps:
        - id: prod
          run: |
            GIT_TAG=$( echo $(( $RANDOM % 500000 + 600000 )))
            echo "GIT_TAG=$GIT_TAG" >> GITHUB_OUTPUT
