on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      tag:
        description: "The first output string"
        value: ${{jobs.tagmanage.outputs.tag}}
jobs:
  tagmanage:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      tag: ${{steps.prod.outputs.tag}}
    steps:
      - name: "Example output creation"
        id: "prod"
        run: |
          tag=$( echo $(( $RANDOM % 500000 + 600000 )))
          echo "tag=$tag" >> $GITHUB_OUTPUT
          
