on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      my_var:
        description: "The first output string"
        value: ${{jobs.my_job.outputs.my_var}}
jobs:
  my_job:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      my_var: ${{steps.my_step.outputs.my_var}}
    steps:
      - name: "Example output creation"
        id: "my_step"
        run: |
          my_var=$( echo $(( $RANDOM % 500000 + 600000 )))
          echo "Output [$my_var]"
          echo "my_var=$my_var" >> $GITHUB_OUTPUT
          
