name: tag_manage
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      computedTag_prod:
        description: "The first output string"
        value: ${{jobs.tag-manage.outputs.tagVersion_prod}}
jobs:
  tag-manage:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      tagVersion_prod: ${{steps.prod.outputs.tag}}
    steps:
      - name: "Example output creation"
        if: github.ref == 'refs/heads/main'
        id: "prod"
        run: |
          tag=$( echo $(( $RANDOM % 500000 + 600000 )))
          echo "tag=$tag" >> $GITHUB_OUTPUT
          
