name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      computedTag:
        description: "The first output string"
        value: ${{ jobs.tagmanage.outputs.tagversion }}
        
jobs:
  tagmanage:
      name: Generate output
      runs-on: ubuntu-latest
      # Map the job outputs to step outputs
      outputs:
        tagversion: ${{ steps.prod.outputs.GIT_TAG }}
      steps:
        - id: prod
          run: |
            GIT_TAG=123456
            echo "GIT_TAG=$GIT_TAG" >> GITHUB_OUTPUT
          
