name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.GIT_TAG }}
        
jobs:
  example_job:
      name: Generate output
      runs-on: ubuntu-latest
      # Map the job outputs to step outputs
      outputs:
        output1: ${{ steps.step1.outputs.GIT_TAG }}
      steps:
        - id: step1
          run: |
            GIT_TAG=$(echo "34567")
            echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_OUTPUT
